// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOA0Tvxa1W05Hj9L3UxhF4Mx25JrzlhNo',
    appId: '1:733758371577:web:357dc6129e8f0600f99428',
    messagingSenderId: '733758371577',
    projectId: 'careerinfo-73e51',
    authDomain: 'careerinfo-73e51.firebaseapp.com',
    storageBucket: 'careerinfo-73e51.firebasestorage.app',
    measurementId: 'G-XPER9XTW1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1V_tBUVMa-Dj1pNh2L1DsKeQZrKqg350',
    appId: '1:733758371577:android:dfb53cd2f56af956f99428',
    messagingSenderId: '733758371577',
    projectId: 'careerinfo-73e51',
    storageBucket: 'careerinfo-73e51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmvVj17w6q0bgUnuSxmBXou0boibv5gDc',
    appId: '1:733758371577:ios:5655db78d10f01f6f99428',
    messagingSenderId: '733758371577',
    projectId: 'careerinfo-73e51',
    storageBucket: 'careerinfo-73e51.firebasestorage.app',
    iosBundleId: 'com.example.careerinfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmvVj17w6q0bgUnuSxmBXou0boibv5gDc',
    appId: '1:733758371577:ios:5655db78d10f01f6f99428',
    messagingSenderId: '733758371577',
    projectId: 'careerinfo-73e51',
    storageBucket: 'careerinfo-73e51.firebasestorage.app',
    iosBundleId: 'com.example.careerinfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOA0Tvxa1W05Hj9L3UxhF4Mx25JrzlhNo',
    appId: '1:733758371577:web:91e84b204919609ef99428',
    messagingSenderId: '733758371577',
    projectId: 'careerinfo-73e51',
    authDomain: 'careerinfo-73e51.firebaseapp.com',
    storageBucket: 'careerinfo-73e51.firebasestorage.app',
    measurementId: 'G-9L4TLNERKZ',
  );
}
